[versions]
androidxAppcompat = "1.6.1"
androidxConstraintlayout = "2.1.4"
androidxCore = "1.9.0"
androidxTestEspressoCore = "3.5.1"
androidxTestJunit = "1.1.5"
material = "1.8.0"
junit4 = "4.13.2"

androidApplication = "7.4.0"
androidLibrary = "7.4.0"
kotlin = "1.7.21"
ktlint = "11.0.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestEspressoCore" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestJunit" }
material = { module = "com.google.android.material:material", version.ref = "material" }
junit = { module = "junit:junit", version.ref = "junit4" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidApplication" }
android-library = { id = "com.android.library", version.ref = "androidLibrary" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
